### ISSUE TITLE
use unittest.mock instead of mock

### ISSUE THREAD

**Issue by pgajdos** [minio/minio-py#1187]
Could you please consider to use unittest.mock at least as a fallback?

**Comment by balamurugana** [comment]
Feel free to send a fix. What is the problem you are facing?

**Comment by mcepl** [comment]
Fix is quite simple:

```sh
$ sed -i 's:import mock:import unittest.mock as mock:' tests/unit/*.py
```

and we (openSUSE) are trying to eliminate unnecessary packages from our distro as many as possible. Independent `mock` is actually not necessary most of the time, it is mostly used only because upstream maintainers forgot to remove it, so we are going through all our packages and trying to eliminate it.
