### ISSUE TITLE
minio 7.2.1 requires urllib3>=2.0

### ISSUE THREAD

**Issue by ydc-0** [minio/minio-py#1378]
## Issue
- minio 7.2.1 can not work with urllib3 1.x, but `urllib3>2.0` is not in `install_requires`.
- Since urllib3 2.0 is less than one year, There are still some other packages that do not support urllib3 2.x. It would be better if minio is still compatible with urllib3 1.x.

- https://github.com/urllib3/urllib3/blob/main/CHANGES.rst#200-2023-04-26

  > 2.0.0 (2023-04-26)
  > Added urllib3.response.BaseHTTPResponse class. All future response classes will be subclasses of BaseHTTPResponse (https://github.com/urllib3/urllib3/issues/2083).

- https://github.com/minio/minio-py/pull/1367/files
  > `- from urllib3 import HTTPResponse`
  > `+ from urllib3.response import BaseHTTPResponse `

## To reproduce

```bash
pip install urllib3\<2.0
pip install minio==7.2.1
python -c 'import minio'
```

## Failure Logs

```bash
➜  ~ pip install urllib3\<2.0
...
Successfully installed urllib3-1.26.18

➜  ~ pip install minio 
...
Successfully installed argon2-cffi-23.1.0 argon2-cffi-bindings-21.2.0 minio-7.2.1 pycryptodome-3.19.0

[notice] A new release of pip is available: 23.3.1 -> 23.3.2
[notice] To update, run: pip install --upgrade pip

➜  ~ python -c 'import minio'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "***/.pyenv/pyenv/versions/3.11.4/lib/python3.11/site-packages/minio/__init__.py", line 41, in <module>
    from .api import Minio
  File "***/.pyenv/pyenv/versions/3.11.4/lib/python3.11/site-packages/minio/api.py", line 44, in <module>
    from urllib3.response import BaseHTTPResponse
ImportError: cannot import name 'BaseHTTPResponse' from 'urllib3.response' (***/.pyenv/pyenv/versions/3.11.4/lib/python3.11/site-packages/urllib3/response.py)

```

**Comment by balamurugana** [comment]
Feel free to send a PR

**Comment by ydc-0** [comment]
@balamurugana  Do you prefer to add `urllib3>2.0` to `install_requires` or make minio compatible with `urllib 1.x`?

**Comment by balamurugana** [comment]
> @balamurugana Do you prefer to add `urllib3>2.0` to `install_requires` or make minio compatible with `urllib 1.x`?

@ydc-0 `urllib3>2.0` to `install_requires`

**Comment by mwagnurr** [comment]
7.2.0 was still working without issues and just now our pipelines are breaking due to these urllib3 errors. I don't understand why this breaking change was introduced with a patch version in https://github.com/minio/minio-py/releases/tag/7.2.1 

If I'm not missing something then just adding `urllib3>=2.0` to `install_requires` will not change the fact that this is a breaking change, which is why I would suggest that the changes in 7.2.1 are reverted and instead released with a proper major version increase

**Comment by balamurugana** [comment]
What is the error you are getting?

**Comment by anehx** [comment]
We're having this issue as well. I'd really suggest that we add support for urllib 1 and 2 instead of forcing the v2 version **just because of typing**..

I'll try to find the time to submit a PR for this.

**Comment by anehx** [comment]
I investigated a little further: The only issue is the import of `BaseHTTPResponse` which `minio` uses for typing.

This class was added in `urllib3` v2 and does not exist in v1. IMO we have multiple options to resolve this:

1. We add `urllib3>=2` as dependency in `install_requires` [(as mentioned here)](https://github.com/minio/minio-py/issues/1378#issuecomment-1869524013) - **this would force all applications using minio to downgrade to version `7.2.0` just because of typing.**
2. We use `try / catch` to import `HTTPResponse` instead of `BaseHTTPResponse` if the app uses version 1 of urllib3. This would work, but we'd tell the typing system that `HTTPResponse` is the same as `BaseHTTPResponse` which is simply not true.
3. We import `HTTPResponse` and use that in our typing.

What do you think is the way to go @balamurugana @mwagnurr @ydc-0 ?

**Comment by balamurugana** [comment]
@anehx I suggest to use `urllib3>=2` i.e. no change. `urllib3 v1` is in maintenance mode and it won't get any new feature. Users of `urllib3 v1` and don't want to upgrade to `urllib3 v2` could use minio-py v7.2.0

**Comment by ydc-0** [comment]
@anehx In fact, I'm still using `minio==7.2.0` in my project, because there are other packages that require `urllib3<2`. 

BTW,  `pip install minio urllib3<2` will still install minio==7.2.1, must add `minio!=7.2.1` or `minio<=7.2.0` to `requirements.txt` when using `urllib3<2`

```
✗ pip install minio urllib3<2
    Uninstalling minio-7.2.2:
      Successfully uninstalled minio-7.2.2
Successfully installed minio-7.2.1 urllib3-1.26.18   # do not work

✗ pip install minio!=7.2.1 urllib3\<2
Successfully installed minio-7.2.0

✗ pip install --upgrade minio urllib3\<2
Successfully installed minio-7.2.2 urllib3-2.1.0
```

**Comment by ydc-0** [comment]
@balamurugana Is it possible to avoid pip install `minio==7.2.1` by default when there are `urllib3<2`? May `yank` the version?: https://peps.python.org/pep-0592/
