### ISSUE TITLE
Understanding for docs on set_bucket_replication() API

### ISSUE THREAD

**Issue by aliou-sidibe** [minio/minio-py#1392]
Hi, i need to execute the set_bucket_replication() method (https://min.io/docs/minio/linux/developers/python/API.html#set_bucket_replication) in my API, which uses several Minio servers for data storage.
I can't find a way to generate the bucket ARN of the Destination class and "REPLACE-WITH-ACTUAL-ROLE".

Does anyone know how to do this?

```python
client = Minio(..)

config = ReplicationConfig(
  "REPLACE-WITH-ACTUAL-ROLE",
  [
      Rule(
          Destination(
              "REPLACE-WITH-ACTUAL-DESTINATION-BUCKET-ARN",
          ),
          ENABLED,
          delete_marker_replication=DeleteMarkerReplication(
              DISABLED,
          ),
          rule_filter=Filter(
              AndOperator(
                  "TaxDocs",
                  {"key1": "value1", "key2": "value2"},
              ),
          ),
          rule_id="rule1",
          priority=1,
      ),
  ],
)
client.set_bucket_replication("my-bucket", config)
```

**Comment by balamurugana** [comment]
Refer https://min.io/docs/minio/linux/administration/bucket-replication/enable-server-side-one-way-bucket-replication.html, https://min.io/docs/minio/linux/administration/bucket-replication.html and https://docs.aws.amazon.com/AmazonS3/latest/API/API_PutBucketReplication.html

**Comment by balamurugana** [comment]
Refer https://min.io/docs/minio/linux/reference/minio-mc-admin/mc-admin-bucket-remote.html#command-mc.admin.bucket.remote

**Comment by P1ng-W1n** [comment]
I feel that the current documentation is lacking a little bit, mainly because of two reasons:

First reason: The documentation states that REPLACE-WITH-ACTUAL-DESTINATION-BUCKET-ARN should be used to define the replication policy. However, to get an ARN, you should already have to have your remote registered.

The mc client does this via a PUT request against the /minio/admin/v3/set-remote-target?bucket=BUCKETNAME endpoint, but the current python admin implementation doesn't seem to have this capability.
// NOTE: This request has some encrypted data in it , so crafting it from scratch doesn't seem to be an option.

Is this something that could be added?
