### ISSUE TITLE
[Feature request] Add option for timeout

### ISSUE THREAD

**Issue by halfcrazy** [minio/minio-py#473]
In some scenario such as network not connecting, file too large. We'd better have an option for timeout.

**Comment by halfcrazy** [comment]
Copy from readme.
Timeout options may look  like below.
minioClient.make_bucket("maylogs", location="us-east-1", timeout=10)
minioClient.fput_object('maylogs', 'pumaserver_debug.log', '/tmp/pumaserver_debug.log', timeout=10)

**Comment by hashbackup** [comment]
Rather than put a timeout option on every API call, I'd prefer to set the timeout option when the client is created.  Is that something that would be accepted if I take a look at doing that?  

I'm trying to replace boto with minio, so having a timeout would be nice.  Setting a default socket timeout is not so great: if communicating with multiple remote services, they'd all get the same timeout.

**Comment by harshavardhana** [comment]
> Rather than put a timeout option on every API call, I'd prefer to set the timeout option when the client is created. Is that something that would be accepted if I take a look at doing that?

Yes that is what i was thinking, APIs shouldn't be disturbed.
