### ISSUE TITLE
V2 signature support

### ISSUE THREAD

**Issue by hashbackup** [minio/minio-py#490]
DreamHost / DreamObjects supports V4 signatures, but Google Storage in S3-compatible mode doesn't.  The minio-go library supports V4 and V2 signatures to be compatible with Google Cloud Storage, but it seems the Python lib doesn't:
```
Traceback (most recent call last):
  File "mintest.py", line 37, in <module>
    for obj in objects:
  File "minio/api.py", line 958, in list_objects
    headers=headers)
  File "minio/api.py", line 1830, in _url_open
    region = self._get_bucket_region(bucket_name)
  File "minio/api.py", line 1764, in _get_bucket_region
    region = self._get_bucket_location(bucket_name)
  File "minio/api.py", line 1802, in _get_bucket_location
    raise response_error.get(bucket_name)
minio.error.ResponseError: ResponseError: code: SignatureDoesNotMatch, message: The request signature we calculated does not match the signature you provided. Check your Google secret key and signing method., bucket_name: xxx, object_name: None, request_id: , host_id: , region: 
```
It would be great to  have Google Storage compatibility in the Python version too.

I looked at the Go version (don't know Go), and it seems to be checking the host name for 'storage.googleapis.com'.   A more general / automatic way (like minio's automatic bucket location detection) might be to start out using V4 signatures.  If a SignatureDoesNotMatch error is thrown while using V4 signatures, set the client for V2 signatures.  If a SignatureDoesNotMatch error occurs while using V2 signatures, fail.  

Or, for my use, I don't mind passing an additional arg when creating the client, like sigversion=2 or 4.  I already have a small config file and can add a new field for this.  Since any future S3-compatible storage will more than likely be V4, maybe this is the easiest way.

**Comment by harshavardhana** [comment]
In minio-go we had a special requirement. But Google cloud storage S3 compatiblity is broken there are many features which do not work as expected. Also support for signature v2 was done for legacy reasons such that `mc` works fine so that users can copy the data out from Google Cloud Storage to a proper S3 compatible implementation.

It is a problem of Google Cloud Storage to have broken S3 frontend while only supporting legacy signature. We don't wish to complicate the library further to add custom behaviors for specific endpoints where underlying implementation is not fully S3 compatible.

It is better to use native GCS Python library to access their storage.
