### ISSUE TITLE
stat_object incorrectly parses last_modified

### ISSUE THREAD

**Issue by Nyoroon** [minio/minio-py#557]
```python
http_time_format = "%a, %d %b %Y %H:%M:%S GMT"
last_modified = mktime(strptime(last_modified, http_time_format))
```
`mktime` parses `strptime` tuple as if it's in local timezone, not GMT.
Maybe just use `email.utils.parsedate` or replace mktime with `calendar.timegm()`?

**Comment by vadmeste** [comment]
stat_object() documentation (https://docs.minio.io/docs/python-client-api-reference#stat_object) conflicts with the real behavior. stat_object() is actually returning float to represent last modified field and not time.time as mentioned in the documentation.

One simple fix is to update the documentation to say that we are returning the last modified field in seconds in local time and not UTC.

However, if we want to enhance the API, it is probably good if we use datetime type since it contains timezone info.

**Comment by harshavardhana** [comment]
We should convert to datetime format. It might break the API though.  Is it true with PutObject() and GetObject() responses as well?

**Comment by vadmeste** [comment]
> Is it true with PutObject() and GetObject() responses as well?

No, put_object returns etag, and get_object returns urllib3.response.HTTPResponse

**Comment by harshavardhana** [comment]
> No, put_object returns etag, and get_object returns urllib3.response.HTTPResponse

I think fget_object returns stat. which is perhaps the same as stat_object, we might have to make a breaking change here and return time itself not seconds.
