### ISSUE TITLE
Why not use boto?

### ISSUE THREAD

**Issue by guettli** [minio/minio-py#560]
There is the boto library for accessing s3.

Could you please tell us why you think your solution is better?

It would be great, if you could update the README. I guess other people have the same question on their mind.

Thank you for sharing your solution!

**Comment by DrJackilD** [comment]
@guettli I can share my experience, why we choose to use `minio` in our project instead of `boto3`

1. Size. As far as we use only S3 from AWS, we don't need all APIs in our code base.
2. Higher level of abstraction. Boto3 is a great library, but it just a thin wrapper around requests library with some additional features. With minio you have easy and understanding API.
3. Very responsive developers and community. May be this is not a cornerstone, but I like a lot of how fast my PRs are reviewed and merged to the master branch.

I hope this will help you to make your choice :)

**Comment by poornas** [comment]
Thanks @DrJackilD, we couldn't have said it better.

**Comment by deekoder** [comment]
@guettli  Boto project is really cool. I just checked it out. 

Minio is a full-fledged object storage server that you can take and host on your own anywhere in the cloud. It's  very easy to set up and you can get it up and running in a few minutes. We offer a tool called mc to do CLI operations and can be used in automation. We offer a suite of SDK bindings for applications to programatically work with any object storage server. Minio Python SDK is one of them. Minio server also can run in a special mode called gateway and has support for notifications which you can then use to do lambda compute. I welcome you to check out our docs at https://docs.minio.io. We love helping other devs be successful in their tasks. https://minio.slack.com/ is where we hang. Come say hello to us there!

**Comment by guettli** [comment]
No question left - Thank you for your replies. Yes, close this

**Comment by guettli** [comment]
No question left - Thank you for your replies. Yes, this issue is resolved.
