### ISSUE TITLE
[Bug] Multipart Upload - InvalidPart Order

### ISSUE THREAD

**Issue by cheveyo20** [minio/minio-py#594]
Hi,

i am using minio and minio py inside a docker swarm. If i run the basic upload file example with fput, i am getting the error InvalidPart Order - The list of parts was not in ascending order. The parts list must be specified in order by part number

This error only happens inside a docker swarm(but every time!). Idependly that this might be a docker network issue, minio-py should be able to handle such networking issues: 
My wireshark analysis one working example (outside docker swarm) and one failing example (inside docker swarm):

working
![2017-11-17 11_02_14-minio_out_working_1a dump](https://user-images.githubusercontent.com/30328572/32943099-582bdc50-cb8b-11e7-86b8-1093fa1a9de8.png)

failing
![2017-11-17 11_01_55-minio_out_failing_1c dump](https://user-images.githubusercontent.com/30328572/32943100-5846b778-cb8b-11e7-8369-d4969ace32e3.png)

**Comment by vadmeste** [comment]
Hey @cheveyo20,

This issue has already been fixed recently: https://github.com/minio/minio-py/commit/68097876f799592771b077e4388b149331849e8c but it is not released yet.

You can download the code from master and test with it.

Meanwhile, I will see if I can push the team to release this fix since this is a important bug.

**Comment by harshavardhana** [comment]
We will make a release today.

**Comment by harshavardhana** [comment]
3.0.0 released with a fix.  Closing this bug please open new bugs for further issues.
