### ISSUE TITLE
urllib3 Connection pool is full

### ISSUE THREAD

**Issue by koliyo** [minio/minio-py#638]
When uploading large files I'm getting a lot of
`WARNING:urllib3.connectionpool:Connection pool is full, discarding connection` messages.

The file seems to be synced alright, but the warning messages are a bit annoying, and are probably there for a reason?

Seems related to https://github.com/minio/minio-py/pull/518

**Comment by ericman93** [comment]
+1
And after a while `MaxRetryError` is raised.
I'm using minio server with docker

**Comment by ohmystack** [comment]
+1
It seems that the multipart uploading causes the issue, not the connection pool.
I have tried to use AWS S3 boto3 client instead of minio-py, the same problem. Maybe it's a minio server's issue.
Here's a work-around I'm using, directly use the [`_do_put_object`](https://github.com/minio/minio-py/blob/3.0.4/minio/api.py#L1410) function.
