### ISSUE TITLE
Asyncio API

### ISSUE THREAD

**Issue by koliyo** [minio/minio-py#719]
What about asyncio enabled API? I see some mention of it here: https://github.com/minio/minio-py/pull/536

I think it deserves an issue for discussion or clarification on status/roadmap.

**Comment by harshavardhana** [comment]
There is no such requirement as of now for async IO - S3 APIs are atomic and current APIs serve all the purpose.

Can you elaborate what current APIs don't satisfy ?

**Comment by koliyo** [comment]
The usecase is transferring many small files concurrently. Right now I have to resort to using threads, something like
```py
    executor = concurrent.futures.ThreadPoolExecutor(
        max_workers=numWorkers,
    )

    pushResults = [
        loop.run_in_executor(executor, self.push)
        for _ in range(numWorkers)
    ]
```

I am not CPU-bound, so using threads is unnecessary if non-blocking async API was available.

**Comment by harshavardhana** [comment]
Yes but Async API is not how S3 APIs behave, we can't see how it is useful. Mimicking Async API on a synchronous API is not useful and is unnecessarily complex. 

What you are doing seems correct and is the right approach here if you want concurrency.

**Comment by koliyo** [comment]
Alright, thanks for responding!

I still think this sort of IO-heavy APIs is where async operations really shines :)

**Comment by harshavardhana** [comment]
Generally such APIs are useful for filesystem operations, where commit is a call back and you have some sort of epoll thread which queues and deques Async events.

But in S3 that is not the case PUT ( write ) completes as soon you are done sending the data and you will get a response right away after a complete of PUT. 

You can still write some Async thread to poll for this but it's not meaningful with the complexity it might bring in - you will have to come up with newer abstractions.

Our APIs are very simple and predictable - they are kept so on purpose by design.

**Comment by SoerenBusse** [comment]
We're quiet iritated about this statement (although it's two years old). I completely agree that S3 is an atomic api, but what's about the network latency. When you're in Europe and try to get an object from a minio instance running in australia you're having a RTT of about 300ms. When running the S3 requests sync you will block your whole application for 300ms, which isn't tolerable. 

Is there a way to do the network part of minio async?
