### ISSUE TITLE
put_object should support file-like objects with an undefined length

### ISSUE THREAD

**Issue by ddevault** [minio/minio-py#844]
I've structured my code to produce a file-like object which dynamically generates its contents as its being read. I would like to avoid generating the object upfront to measure its length, because it could be rather large and I don't have anywhere to put it. I don't want to generate it twice, measuring and discarding the first time, then uploading it the second time, because it could change during this time and generating this object is a computationally expensive process.

Instead, I should be able to put_objects with an undefined length, and specify the chunk size manually.

**Comment by harshavardhana** [comment]
AWS S3 doesn't support objects with undefined content-length so we don't support either.

Once AWS S3 supports it we can support too. Closing this issue.

**Comment by ddevault** [comment]
minio is broadly opposed to implementing features which S3 does not have?

**Comment by harshavardhana** [comment]
Yes @ddevault there is no good reason to deviate, unless there is a stronger commercial requirement.

**Comment by ddevault** [comment]
That's pretty disappointing. I wouldn't even know where to start with petitioning AWS to add this, I'm not an AWS customer.

**Comment by KentBrockman** [comment]
> Yes @ddevault there is no good reason to deviate, unless there is a stronger commercial requirement.

@harshavardhana I believe @ddevault  is providing a good reason to deviate - making `length` optional means not having to precompute a large object, just to calculate its length, to provide as an argument to `put_object`. 

Precomputing the entire object can be expensive or undoable. Making it optional avoids all of these costs and compromises to make a more efficient, faster and elegant API. Put another way, at the time we are ready to put the object to minio, it is unknown how long the stream is. Every way to determine the length of the bytes has considerable drawbacks. To elaborate:

- Consider the CPU time to create the object, just to get `length`, then compute the object again to supply it as `data` to `put_object`. This duplicates the CPU operation twice and any associated resources. Also consider what happens if the content generation process is stocastic or non-deterministic? In that case, it would be impossible to precompute this way because the content-length might change between runs.
- Say instead you do the CPU operation once and store the resulting object entirely in memory. This lets me compute `length` for `put_object` and then I can pass the object from memory as `data` to `put_object`. This works unless the object itself is too big to fit into memory - which is going to be the case for large files. Even if the files are not large, any design is fundamentally memory unsafe. This is challenging for any developer running multiple processes competing for RAM (browser, chat clients, text editor or IDE, etc,) or running a lower powered machine. From a server standpoint, I may have to over-provision RAM for similar reasons and at the very least determine requirements for largest file which might change as requirements often do. Memory-leaky software is painful to administer and use - fortunately in this case there appears to be a way to make it memory safe without many tradeoffs.
- Instead of storing the object in memory, maybe we write to disk and compute the length that way and upload either through `put_object` or `fput_object`. This requires me to provision enough block storage space on my server (costs more $$) or simply have that free disk space on my development machine (hassle and/or $$). This also incurs a bunch of disk IO, which adds wear and tear on hardware. If this were unavoidable this would be the best workaround, but in this case, the proposed API change could avoid all of this trouble altogether.

The amount of time, effort and hardware associated with workarounds above sound like strong commercial grounds for this recommendation to me :+1:

**Comment by ddevault** [comment]
Sorry to bump an old issue. Is this not feasible with [multipart uploads](https://aws.amazon.com/blogs/aws/amazon-s3-multipart-upload/)? The multipart S3 API on AWS does not appear to require you to specify the content length in advance.

**Comment by balamurugana** [comment]
@ddevault  The feature is added in the PR https://github.com/minio/minio-py/pull/968

**Comment by ddevault** [comment]
Thanks!

**Comment by ddevault** [comment]
@balamurugana what am I supposed to use for the length field in this case?

**Comment by balamurugana** [comment]
Just pass length=-1 and part_size=valid-size.

**Comment by ddevault** [comment]
Thanks. Would be good to document that.
